
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - storage.yo.gcs
  resources:
  - gcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.yo.gcs
  resources:
  - gcs/finalizers
  verbs:
  - update
- apiGroups:
  - storage.yo.gcs
  resources:
  - gcs/status
  verbs:
  - get
  - patch
  - update
